#!/usr/bin/env python3
import duckdb

# project_path = "introduction-to-dbt/nyc_yellow_taxi/"

con = duckdb.connect("dbt.duckdb", read_only=True)

print(con.sql("show tables"))


def print_table(query: str):
    print(query)
    print(con.sql(query))


print_table("select * from taxi_rides_raw limit 10")
print_table("select count(*) as total_rides from taxi_rides_raw")
print_table("select * from total_creditcard_riders_by_day")
print_table("select * from nynj_zipcodes")
